### ISSUE TITLE
No addon on the palette

### ISSUE THREAD

**Issue by jkdobro** [software-bits/node-red-contrib-device-monitor#3]
After installing the add-on (via Manage Palette) it does not appear in the palette.
In Manage Palette node device-monitor has a gray mark (not active?)
What group name is used for it in the palette (this information is missing in the documentation)?

**Comment by adischerrer** [comment]
Same issue here.

**Comment by software-bits** [comment]
Thank you for reaching out @jkdobro and @adischerrer!
Sorry for the late reply. I did some investigation and the issue seems to be related to the way dependencies are required vs how these are resolved by node-red.

For the time being try to install directly via npm by going to your `.node-red/` directory and running `npm install node-red-contrib-device-monitor`.

By doing so the dependencies should be resolved as intended and the node should appear under 'Network' group.
When I find some time I will try to resolve the issue and make it installable via the 'Palette' as well.

**Comment by Alekeep** [comment]
Installed via "Palette" as well as npm uninstall... install... rebuild... and still not finding the addon.
Any guidance on another workaround? This seems to be a very helpful tool if I am able to use it.
Thanks!

-  node-red v3.1.4
-  node.js v21.6.1

**Comment by efelmer** [comment]
Same issue here. Initially tried installing via Node Red Palette manager, and it didn't show up in available nodes. Deleted the package and installed using 'sudo npm install node-red-contrib-device-monitor' in .node.red folder, restarted Node red, refreshed browser, still doesn't show up. Any insight on when you can fix this?

**Comment by dgruhn-akamai** [comment]
Same issue. Looks like a good package, any progress on this?
